# -*- coding: utf-8 -*-
"""Final Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h8bDjfeToHNcFpChjZIf-FZrqOdFR7Ap
"""



import os
import tweepy as tw
import pandas as pd
import csv

consumer_key = "hmaOrIakxrCNvTyq2TxxidvdD"
consumer_secret = "wh3COLQ2gI5P8ANH2HVem5IL9izhFfjxZU6ECdMrbQzdVLnau1"
access_token = "982322496-ztIAlKnbVIuoqgJ7lrGZoM9ytd3V1ibaZNMp5Z3n"
access_token_secret = "IT1puLiz6UXfSQXqTXb7lJzetT2LCQuCdE6O0dlbb8GLl"
auth = tw.OAuthHandler(consumer_key, consumer_secret)

auth.set_access_token(access_token, access_token_secret)
api = tw.API(auth, wait_on_rate_limit=True)


# Collect tweets

date_since = "2021-11-30"
#"vaccination","COVID", "biontech", "pfizer" ,"sinovac", "sputnik","moderna","johnson", "janssen" 
search_words ="vaccination OR COVID OR biontech OR pfizer OR sinovac OR sputnik OR moderna OR johnson OR janssen -filter:retweets" 

#johnson OR #covid19 -filter:retweets" 
tweets = tw.Cursor(api.search_tweets, 
              q="vaccination OR COVID OR biontech OR pfizer OR sinovac OR sputnik OR moderna OR johnson OR janssen -filter:retweets since:2021-11-30 until:2021-12-03",
              lang="en",
              tweet_mode = "extended",
              ).items(1000)

csvFile = open('final_tweets.csv', 'w')
#Use csv writer
csvWriter = csv.writer(csvFile)

for tweet in tweets:
    tweet_text = tweet.full_text.lower()
    if ("vaccination" in tweet_text) or ("covid" in tweet_text) or ("biontech" in tweet_text) or ("pfizer" in tweet_text) or ("sinovac" in tweet_text) or ("sputnik" in tweet_text) or ("moderna" in tweet_text) or ("johnson" in tweet_text) or ("janssen" in tweet_text):
        print(tweet.full_text)
        csvWriter.writerow([tweet.full_text])


csvFile.close()

